### ISSUE TITLE
Any plans to move to Babel 6 and use .babelrc

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-hugeapp#30]
I could make these changes myself locally (and have in a copy), but don't want to wipe them out on a version update or have to merge every release.

**Comment by tomitrescak** [comment]
:+1: would be great!!!

**Comment by bySabi** [comment]
I make a PR for Babel 6 upgrade here: https://github.com/thereactivestack/kickstart-hugeapp/pull/31
But is seen have a problem and I don´t know where.
Need some more fix & test.
`flow-router` and `simple` app version is working fine on Babel 6 upgrade

**Comment by eXon** [comment]
I'll try to debug this when I have a few minutes. Should be this week.

**Comment by eXon** [comment]
Done :)

**Comment by tomitrescak** [comment]
Guys, I know you are not a support line, and when running a fresh copy of the project all works peachy. But I have problems upgrading my existing project to babel 6. I have copied all 3 configes to their places and also updated the webpack npm json file. All builds well buy I get a following error before runing the server:

```
=> Errors prevented startup:

   While processing files with webpack:webpack (for target os.osx.x86_64):
   entry/server/webpack.conf.js: ./modules/ClaraApp/server/main.ts
   Module build failed: TypeError: /Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/modules/ClaraApp/server/main.ts: Cannot call method 'indexOf' of undefined
   at Object.relative (/Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/source-map/lib/util.js:206:18)
   at SourceMapConsumer_generatedPositionFor [as generatedPositionFor]
   (/Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/source-map/lib/source-map-consumer.js:730:23)
   at /Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:444:53
   at Array.forEach (native)
   at SourceMapConsumer_eachMapping [as eachMapping] (/Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/source-map/lib/source-map-consumer.js:155:16)
   at /Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:443:26
   at File.mergeSourceMap (/Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:468:9)
   at File.generate (/Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:662:25)
   at File.transform (/Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:509:17)
   at /Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/pipeline.js:46:19
   at File.wrap (/Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:519:16)
   at Pipeline.transform (/Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/pipeline.js:43:17)
   at transpile (/Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/babel-loader/index.js:14:22)
   at Object.module.exports (/Users/tomi/Documents/Programming/Github/Clara-Kickstart-FlowRouter/.meteor/local/webpack-npm/node_modules/babel-loader/index.js:87:14)
   @ ./entry/server/entry.js 3:0-31
```

Any idea? Thanks

**Comment by tomitrescak** [comment]
I managed to solve the previous issue which was a bug in the sourcemap loader for the babel 6.

**Comment by tomitrescak** [comment]
Guys, yet one more problem appeared on CI servers when suddenyl all build fail on error below. All works OK locally, but fails in cloud. It complains with babel-plugin-transform-legacy. Do you have any idea what could be the problem? I am using Codeship:

```
Welcome to Modulus
You are logged in as tomi.trescak@gmail.com
Selecting Clara

Meteor project detected...

WARNING: The output directory is under your source tree.

Installing local NPM...
npm WARN invalid config loglevel="quiet"
npm@2.14.15 .meteor/local/webpack-npm/node_modules/npm
Installing NPM dependencies for the web bundle...
WARN engine postcss@5.0.13: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.14.15"})
WARN engine deasync@0.1.1: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.40","npm":"2.14.15"})
WARN engine csso@1.4.4: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.14.15"})
npm WARN optional dep failed, continuing fsevents@1.0.6

> deasync@0.1.1 install /home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/awesome-typescript-loader/node_modules/deasync
> node ./build.js

`linux-x64-node-0.10` exists; testing
Binary is fine; exiting
npm WARN prefer global npm@2.14.15 should be installed with -g
null-loader@0.1.1 node_modules/null-loader

react-transform-catch-errors@1.0.0 node_modules/react-transform-catch-errors

classnames@2.2.1 node_modules/classnames

marked@0.3.5 node_modules/marked

react-mixin@3.0.3 node_modules/react-mixin
object-assign@4.0.1
smart-mixin@1.2.1

url@0.11.0 node_modules/url
punycode@1.3.2
querystring@0.2.0

webpack-hot-middleware@2.6.0 node_modules/webpack-hot-middleware
querystring@0.2.0
strip-ansi@2.0.1 (ansi-regex@1.1.1)

babel-plugin-react-transform@2.0.0-beta1 node_modules/babel-plugin-react-transform
array-find@1.0.0

babel-loader@6.2.0 node_modules/babel-loader
object-assign@4.0.1
loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)

extract-text-webpack-plugin@0.9.1 node_modules/extract-text-webpack-plugin
async@1.5.0
loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)

file-loader@0.8.5 node_modules/file-loader
loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)

style-loader@0.13.0 node_modules/style-loader
loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)

url-loader@0.5.7 node_modules/url-loader
mime@1.2.11
loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)

sweetalert@1.1.3 node_modules/sweetalert

js-beautify@1.5.10 node_modules/js-beautify
config-chain@1.1.9 (ini@1.3.4, proto-list@1.2.4)
nopt@3.0.6 (abbrev@1.0.7)
mkdirp@0.5.1 (minimist@0.0.8)

jstransform-loader@0.2.0 node_modules/jstransform-loader
concat-map@0.0.1
convert-source-map@0.4.1
async@0.9.2
jstransform@8.2.0 (base62@0.1.1, source-map@0.1.31, esprima-fb@8001.1001.0-dev-harmony-fb)

react-transform-hmr@1.0.1 node_modules/react-transform-hmr
global@4.3.0 (process@0.5.2, min-document@2.17.0)
react-proxy@1.1.1 (react-deep-force-update@1.0.0, lodash@3.10.1)

awesome-typescript-loader@0.14.2 node_modules/awesome-typescript-loader
object-assign@2.1.1
colors@1.1.2
bluebird@2.10.2
loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)
deasync@0.1.1 (bindings@1.2.1, nan@2.1.0)
lodash@3.10.1

redbox-react@1.2.0 node_modules/redbox-react
object-assign@4.0.1
error-stack-parser@1.3.1 (stackframe@0.3.1)

moment@2.10.6 node_modules/moment

webpack@1.12.9 node_modules/webpack
interpret@0.6.6
tapable@0.1.10
clone@1.0.2
supports-color@3.1.2 (has-flag@1.0.0)
async@1.5.0
mkdirp@0.5.1 (minimist@0.0.8)
esprima@2.7.1
enhanced-resolve@0.9.1 (graceful-fs@4.1.2, memory-fs@0.2.0)
optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
memory-fs@0.3.0 (errno@0.1.4, readable-stream@2.0.4)
webpack-core@0.6.8 (source-list-map@0.1.5, source-map@0.4.4)
loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)
watchpack@0.2.9 (graceful-fs@4.1.2, async@0.9.2, chokidar@1.4.1)
uglify-js@2.6.1 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.10.0, source-map@0.5.3)
node-libs-browser@0.5.3 (https-browserify@0.0.0, tty-browserify@0.0.0, constants-browserify@0.0.1, string_decoder@0.10.31, path-browserify@0.0.0, os-browserify@0.1.2, process@0.11.2, punycode@1.4.0, querystring-es3@0.2.1, assert@1.3.0, timers-browserify@1.4.2, domain-browser@1.1.7, stream-browserify@1.0.0, events@1.1.0, vm-browserify@0.0.4, console-browserify@1.1.0, util@0.10.3, http-browserify@1.7.0, readable-stream@1.1.13, url@0.10.3, buffer@3.5.5, browserify-zlib@0.1.4, crypto-browserify@3.2.8)

babel-runtime@6.3.19 node_modules/babel-runtime
core-js@1.2.6

babel-plugin-transform-runtime@6.3.13 node_modules/babel-plugin-transform-runtime
babel-runtime@5.8.34 (core-js@1.2.6)

babel-preset-react@6.3.13 node_modules/babel-preset-react
babel-plugin-syntax-jsx@6.3.13 (babel-runtime@5.8.34)
babel-plugin-syntax-flow@6.3.13 (babel-runtime@5.8.34)
babel-plugin-transform-flow-strip-types@6.3.15 (babel-runtime@5.8.34)
babel-plugin-transform-react-jsx-source@6.3.13 (babel-runtime@5.8.34)
babel-plugin-transform-react-display-name@6.3.13 (babel-runtime@5.8.34)
babel-plugin-transform-react-jsx@6.3.13 (babel-helper-builder-react-jsx@6.3.13, babel-runtime@5.8.34)

babel-plugin-transform-decorators-legacy@1.3.1 node_modules/babel-plugin-transform-decorators-legacy
babel-plugin-syntax-decorators@6.3.13 (babel-runtime@5.8.34)
babel-template@6.3.13 (babylon@6.3.18, babel-types@6.3.18, babel-traverse@6.3.19, lodash@3.10.1, babel-runtime@5.8.34)

babel-core@6.3.17 node_modules/babel-core
path-is-absolute@1.0.0
babel-template@6.3.13
slash@1.0.0
shebang-regex@1.0.0
path-exists@1.0.0
babel-messages@6.3.18
babel-helpers@6.3.13
private@0.1.6
convert-source-map@1.1.2
debug@2.2.0 (ms@0.7.1)
minimatch@2.0.10 (brace-expansion@1.1.2)
babel-types@6.3.18 (to-fast-properties@1.0.1, esutils@2.0.2)
babylon@6.3.18
babel-code-frame@6.3.13 (js-tokens@1.0.2, esutils@2.0.2, line-numbers@0.2.0, chalk@1.1.1, repeating@1.1.3)
babel-generator@6.3.19 (trim-right@1.0.1, repeating@1.1.3, is-integer@1.0.6, detect-indent@3.0.1)
babel-traverse@6.3.19 (globals@8.15.0, repeating@1.1.3, invariant@2.2.0)
json5@0.4.0
source-map@0.5.3
lodash@3.10.1
babel-register@6.3.13 (home-or-tmp@1.0.0, source-map-support@0.2.10, core-js@1.2.6)
babel-runtime@5.8.34 (core-js@1.2.6)

jsx-control-statements@2.0.1 node_modules/jsx-control-statements
jstransform@9.1.1 (base62@0.1.1, source-map@0.1.31, esprima-fb@12001.1.0-dev-harmony-fb)
lodash@3.10.1
babel-plugin-syntax-jsx@6.3.13 (babel-runtime@5.8.34)

babel-preset-es2015@6.3.13 node_modules/babel-preset-es2015
babel-plugin-transform-es2015-typeof-symbol@6.3.13 (babel-runtime@5.8.34)
babel-plugin-transform-es2015-block-scoped-functions@6.3.13 (babel-runtime@5.8.34)
babel-plugin-transform-es2015-spread@6.3.14 (babel-runtime@5.8.34)
babel-plugin-check-es2015-constants@6.3.13 (babel-runtime@5.8.34)
babel-plugin-transform-es2015-template-literals@6.3.13 (babel-runtime@5.8.34)
babel-plugin-transform-es2015-arrow-functions@6.3.13 (babel-runtime@5.8.34)
babel-plugin-transform-es2015-literals@6.3.13 (babel-runtime@5.8.34)
babel-plugin-transform-es2015-for-of@6.3.13 (babel-runtime@5.8.34)
babel-plugin-transform-es2015-destructuring@6.3.15 (babel-runtime@5.8.34)
babel-plugin-transform-es2015-unicode-regex@6.3.13 (regexpu@1.3.0, babel-helper-regex@6.3.13, babel-runtime@5.8.34)
babel-plugin-transform-es2015-object-super@6.3.13 (babel-helper-replace-supers@6.3.13, babel-runtime@5.8.34)
babel-plugin-transform-es2015-sticky-regex@6.3.13 (babel-helper-regex@6.3.13, babel-types@6.3.18, babel-runtime@5.8.34)
babel-plugin-transform-es2015-shorthand-properties@6.3.13 (babel-types@6.3.18, babel-runtime@5.8.34)
babel-plugin-transform-es2015-function-name@6.3.19 (babel-types@6.3.18, babel-helper-function-name@6.3.15, babel-runtime@5.8.34)
babel-plugin-transform-es2015-computed-properties@6.3.13 (babel-template@6.3.13, babel-helper-define-map@6.3.13, babel-runtime@5.8.34)
babel-plugin-transform-es2015-modules-commonjs@6.3.16 (babel-plugin-transform-strict-mode@6.3.13, babel-template@6.3.13, babel-types@6.3.18, babel-runtime@5.8.34)
babel-plugin-transform-es2015-block-scoping@6.3.13 (babel-types@6.3.18, babel-template@6.3.13, babel-traverse@6.3.19, lodash@3.10.1, babel-runtime@5.8.34)
babel-plugin-transform-es2015-parameters@6.3.18 (babel-helper-get-function-arity@6.3.13, babel-helper-call-delegate@6.3.13, babel-template@6.3.13, babel-types@6.3.18, babel-traverse@6.3.19, babel-runtime@5.8.34)
babel-plugin-transform-es2015-classes@6.3.15 (babel-helper-optimise-call-expression@6.3.13, babel-helper-replace-supers@6.3.13, babel-messages@6.3.18, babel-helper-function-name@6.3.15, babel-helper-define-map@6.3.13, babel-template@6.3.13, babel-types@6.3.18, babel-traverse@6.3.19, babel-runtime@5.8.34)
babel-plugin-transform-regenerator@6.3.18 (babel-plugin-syntax-async-functions@6.3.13, private@0.1.6, babylon@6.3.18, babel-types@6.3.18, babel-traverse@6.3.19, babel-runtime@5.8.34)

babel-preset-stage-0@6.3.13 node_modules/babel-preset-stage-0
babel-plugin-transform-function-bind@6.3.13 (babel-plugin-syntax-function-bind@6.3.13, babel-runtime@5.8.34)
babel-plugin-transform-do-expressions@6.3.13 (babel-plugin-syntax-do-expressions@6.3.13, babel-runtime@5.8.34)
babel-preset-stage-1@6.3.13 (babel-plugin-transform-class-properties@6.3.13, babel-plugin-transform-class-constructor-call@6.3.13, babel-plugin-transform-export-extensions@6.3.13, babel-plugin-transform-decorators@6.3.13, babel-preset-stage-2@6.3.13)

css-loader@0.23.0 node_modules/css-loader
object-assign@4.0.1
postcss-modules-extract-imports@1.0.0
postcss-modules-scope@1.0.0
postcss-modules-local-by-default@1.0.0
postcss-modules-values@1.1.1 (icss-replace-symbols@1.0.2)
css-selector-tokenizer@0.5.4 (fastparse@1.1.1, cssesc@0.1.0)
source-list-map@0.1.5
lodash.camelcase@3.0.1 (lodash._createcompounder@3.0.0)
loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)
postcss@5.0.13 (js-base64@2.1.9, supports-color@3.1.2, source-map@0.5.3)
cssnano@3.4.0 (decamelize@1.1.1, indexes-of@1.0.1, postcss-normalize-charset@1.1.0, postcss-minify-gradients@1.0.1, postcss-ordered-values@2.0.2, postcss-discard-empty@2.0.0, postcss-reduce-transforms@1.0.3, postcss-discard-duplicates@2.0.0, postcss-zindex@2.0.0, postcss-reduce-idents@2.2.1, postcss-convert-values@2.3.4, postcss-merge-rules@2.0.3, defined@1.0.0, postcss-discard-comments@2.0.2, postcss-value-parser@3.2.3, postcss-filter-plugins@2.0.0, postcss-minify-font-values@1.0.2, postcss-discard-unused@2.1.0, postcss-minify-params@1.0.4, postcss-unique-selectors@2.0.1, postcss-merge-longhand@2.0.1, postcss-merge-idents@2.1.3, postcss-colormin@2.1.7, postcss-calc@5.0.0, postcss-normalize-url@3.0.4, postcss-minify-selectors@2.0.1, postcss-svgo@2.1.1, autoprefixer@6.1.2)

react@0.14.3 node_modules/react
envify@3.4.0 (through@2.3.8, jstransform@10.1.0)
fbjs@0.3.2 (whatwg-fetch@0.9.0, loose-envify@1.1.0, ua-parser-js@0.7.10, promise@7.0.4, core-js@1.2.6)

semantic-ui-css@2.1.6 node_modules/semantic-ui-css
jquery@2.1.4

typescript@1.7.5 node_modules/typescript
Installing NPM dependencies for the server bundle...
npm WARN prefer global npm@2.14.15 should be installed with -g
Errors prevented bundling:
While processing files with webpack:webpack (for target web.browser):
entry/client/webpack.conf.js: ./entry/client/entry.js
Module build failed: ReferenceError: Unknown plugin
"transform-decorators-legacy" specified in "base" at 0, attempted to resolve
relative to "/home/rof/src/github.com/tomitrescak/Clara/entry/client"
at
/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:193:17
at Array.map (native)
at Function.normalisePlugins
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
at OptionManager.mergeOptions
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
at OptionManager.init
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
at File.initOptions
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:190:75)
at new File
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:121:22)
at Pipeline.transform
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
at transpile
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-loader/index.js:14:22)
at Object.module.exports
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-loader/index.js:87:14)

While processing files with webpack:webpack (for target os.linux.x86_64):
entry/server/webpack.conf.js: ./entry/server/entry.js
Module build failed: ReferenceError: Unknown plugin
"transform-decorators-legacy" specified in "base" at 0, attempted to resolve
relative to "/home/rof/src/github.com/tomitrescak/Clara/entry/server"
at
/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:193:17
at Array.map (native)
at Function.normalisePlugins
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
at OptionManager.mergeOptions
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
at OptionManager.init
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
at File.initOptions
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:190:75)
at new File
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:121:22)
at Pipeline.transform
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
at transpile
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-loader/index.js:14:22)
at Object.module.exports
(/home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm/node_modules/babel-loader/index.js:87:14)

[Error] Error: Conversion failed.
```

**Comment by eXon** [comment]
It looks like a caching problem. Have you tried flushing /home/rof/src/github.com/tomitrescak/Clara/.meteor/local/webpack-npm?

**Comment by tomitrescak** [comment]
This is happening on the CI server (Codeship) which spins a new VM instance on each deployment ;( But to be sure I'll add some directives to the CI server and report back. I'll also add to tinstall newest NPM.

**Comment by tomitrescak** [comment]
No luck .. still the same error.
From localhost all is great, but on CI it fails.
CI creates a new VM on every try ;(

**Comment by tomitrescak** [comment]
Guys, am completely stuck ... all 5 projects of mine are failing CI ;(

This is an example (cut down of a CI pass)

```
nvm install 0.10.40
nvm use 0.10.40
curl -o meteor_install_script.sh https://install.meteor.com/
chmod +x meteor_install_script.sh
sed -i "s/type sudo >\/dev\/null 2>&1/\ false /g" meteor_install_script.sh
./meteor_install_script.sh
export PATH=$PATH:~/.meteor/
rm -rf /home/rof/src/github.com/tomitrescak/Clara/.meteor/local
ls -al /home/rof/src/github.com/tomitrescak/Clara/.meteor
meteor --version
```

**Comment by tomitrescak** [comment]
Looks like babel is incorrectly resolving the directory maybe?

Errors prevented bundling:
While processing files with webpack:webpack (for target web.browser):
entry/client/webpack.conf.js: ./entry/client/entry.js
Module build failed: ReferenceError: Unknown plugin
"babel-plugin-transform-decorators-legacy" specified in "base" at 0, attempted
**to resolve relative to
"/home/rof/src/github.com/tomitrescak/Clara/entry/client"**

**Comment by eXon** [comment]
Can you please create a different issue? I don't want to spam other users here and this issue is closed.

**Comment by john-osullivan** [comment]
I'm running into this issue as well!  Did it ever get resolved?
