### ISSUE TITLE
Required Node/NPM version?

### ISSUE THREAD

**Issue by sys13** [thereactivestack/kickstart-hugeapp#34]
What version of Node/NPM do you suggest? I'm getting an error on a fresh 0.10.40 node install.
```
npm WARN prefer global npm@2.14.15 should be installed with -g
npm WARN unmet dependency /home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-preset-stage-0/node_modules/babel-preset-stage-1/node_modules/babel-preset-stage-2/node_modules/babel-preset-stage-3/node_modules/babel-plugin-transform-async-to-generator requires babel-runtime@'^5.0.0' but will load
npm WARN unmet dependency /home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-runtime,
npm WARN unmet dependency which is version 6.3.19
webpack built 393ff39531ddf307fca3 in 2353ms /
Hash: 393ff39531ddf307fca3
Version: webpack 1.12.9
Time: 2353ms
     Asset     Size  Chunks       Chunk Names
    web.js  34.8 kB       0       main
web.js.map  40.8 kB       0       main
chunk    {0} web.js, web.js.map (main) 12.4 kB [rendered]
    [0] multi main 40 bytes {0} [built] [1 error]
    [1] ./.meteor/local/webpack-npm/~/webpack-hot-middleware/client.js?path=http://localhost:3500/__webpack_hmr&reload=true 3.24 kB {0} [built]
    [2] (webpack)/buildin/module.js 251 bytes {0} [built]
    [3] ./.meteor/local/webpack-npm/~/webpack-hot-middleware/~/querystring/index.js 127 bytes {0} [built]
    [4] ./.meteor/local/webpack-npm/~/webpack-hot-middleware/~/querystring/decode.js 2.4 kB {0} [built]
    [5] ./.meteor/local/webpack-npm/~/webpack-hot-middleware/~/querystring/encode.js 2.09 kB {0} [built]
    [6] ./.meteor/local/webpack-npm/~/webpack-hot-middleware/~/strip-ansi/index.js 161 bytes {0} [built]
    [7] ./.meteor/local/webpack-npm/~/webpack-hot-middleware/~/strip-ansi/~/ansi-regex/index.js 145 bytes {0} [built]
    [8] ./.meteor/local/webpack-npm/~/webpack-hot-middleware/client-overlay.js 1.01 kB {0} [built]
    [9] ./.meteor/local/webpack-npm/~/webpack-hot-middleware/process-update.js 2.95 kB {0} [built]

ERROR in ./entry/client/entry.js
Module build failed: Error: Cannot find module 'babel-plugin-transform-es2015-template-literals'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-preset-es2015/index.js:3:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at OptionManager.mergePresets (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:324:28)
    at OptionManager.mergeOptions (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:287:12)
    at OptionManager.init (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
    at File.initOptions (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:190:75)
    at new File (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:121:22)
    at Pipeline.transform (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-loader/index.js:87:14)
 @ multi main
Installing NPM dependencies for the server bundle...
npm WARN prefer global npm@2.14.15 should be installed with -g
npm WARN unmet dependency /home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-preset-stage-0/node_modules/babel-preset-stage-1/node_modules/babel-preset-stage-2/node_modules/babel-preset-stage-3/node_modules/babel-plugin-transform-async-to-generator requires babel-runtime@'^5.0.0' but will load
npm WARN unmet dependency /home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-runtime,
npm WARN unmet dependency which is version 6.3.19
=> Errors prevented startup:                  
   
   While processing files with webpack:webpack (for target os.linux.x86_64):
   entry/server/webpack.conf.js: ./entry/server/entry.js
   Module build failed: Error: Cannot find module
   'babel-plugin-transform-es2015-template-literals'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-preset-es2015/index.js:3:5)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at OptionManager.mergePresets
   (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:324:28)
   at OptionManager.mergeOptions
   (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:287:12)
   at OptionManager.init
   (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
   at File.initOptions
   (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:190:75)
   at new File
   (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/file/index.js:121:22)
   at Pipeline.transform
   (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
   at transpile
   (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-loader/index.js:14:22)
   at Object.module.exports
   (/home/sage/prj/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/babel-loader/index.js:87:14)
```

**Comment by eXon** [comment]
I've done a fresh clone of the repo with NVM setting node to 0.10.40 and everything is working fine. Did you started from a fresh folder? If not, try to clean the .meteor/local/webpack-npm folder.

**Comment by alecperkey** [comment]
Fresh folder solved the same problem for me.

By the way, I also see the same npm warning 'prefer global npm@2.14.15 should be installed with -g'. If that is saying I don't have npm globally installed, than it's an incorrect message. Do you have a better understanding?

**Comment by eXon** [comment]
You can safetly ignore this warning. I'm working on removing NPM at all anyway from the build process and make people run `npm install` by themself (like in Meteor 1.3).
