### ISSUE TITLE
eslint crashing > Error while loading rule 'react/no-multi-comp': context.getSourceCode is not a function

### ISSUE THREAD

**Issue by dcsan** [thereactivestack/kickstart-hugeapp#42]
I got this error popup on opening any JS files in the repo.

I'm not quite sure what to modify, since there's no 'package.json' for the app. 
presumably its using a local installed version on eslint that's included in your repo?

update this fixed it:

> npm install -g eslint react meteor node browser eslint-plugin-react

```
Error: Error while loading rule 'react/no-multi-comp': context.getSourceCode is not a function
TypeError: Error while loading rule 'react/no-multi-comp': context.getSourceCode is not a function
    at Function.componentRule (/Users/dc/dev/rnd/fastchat/app/.meteor/local/webpack-npm/node_modules/eslint-plugin-react/lib/util/Components.js:107:28)
    at /usr/local/lib/node_modules/eslint/lib/eslint.js:732:28
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:710:16)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:199:27)
    at CLIEngine.executeOnText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:430:26)
    at Object.cli.execute (/usr/local/lib/node_modules/eslint/lib/cli.js:147:36)
    at /Users/dc/.atom/packages/linter-eslint/lib/worker.js:78:12
    at /Users/dc/.atom/packages/linter-eslint/lib/worker.js:47:18
    at /Users/dc/.atom/packages/linter-eslint/node_modules/childprocess-promise/node_modules/sb-communication/node_modules/zm-event-kit/dist/Emitter.js:58:16
```

**Comment by ospfranco** [comment]
Just FYI: I had this same problem, but it was caused by not having a .eslintrc file in the project root
