### ISSUE TITLE
Mup deploy fails with react-runtime 0.14.4

### ISSUE THREAD

**Issue by dbismut** [thereactivestack/kickstart-hugeapp#44]
Hey - deploying with `mup deploy` generates the following error when updating to `react-runtime 0.14.4`.

```
=> Archiving failed: ENOENT: no such file or directory, stat '/var/folders/x1/dnq5b_ks3tb3f3j2y4z5x1sh0000gn/T/a2693b7a-d1b6-4223-bf5f-3859605ae106/bundle/programs/server/npm/react-runtime-prod/node_modules/react/node_modules/envify/node_modules/jstransform/node_modules/esprima-fb/.#README.md'
```

`meteor add react-runtime@=0.14.3` fixes the issue. Not sure how this is related to #36.

**Comment by eXon** [comment]
This is weird. I'll take a look when I have a few minutes.

**Comment by dbismut** [comment]
Thanks. It seems to be a mup issue, not yours. https://github.com/arunoda/meteor-up/issues/812

But I would advise reverting back to 0.14.3 until this is resolved?

**Comment by eXon** [comment]
Let me know if it's still a problem.

**Comment by tomitrescak** [comment]
@exon I have a major issue with deploying to Modulus, this is the error I get:

```
Running command: npm start


> meteor-dev-bundle@0.0.0 start /mnt/app/programs/server
> node ../../main




/mnt/app/programs/server/node_modules/fibers/future.js:245
						throw(ex);
						      ^

Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/mnt/app/programs/server/boot.js:150:18)
    at webpack:///server.js:1:1
    at webpack:///server.js:4:1
    at /mnt/app/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/mnt/app/programs/server/node_modules/underscore/underscore.js:79:11)



npm
 ERR! Linux 3.13.0-52-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.40/bin/npm" "start"
npm ERR!
 node v0.10.40
npm ERR! 
npm  v3.8.0
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR!
 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!
     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle

npm ERR! There is likely additional logging output above.



npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/programs/server/npm-debug.log

Now using node v0.10.40

Found package.json: ./programs/server/package.json

Start script specified in package.json: node ../../main
```

Looks like npm in NOT installing what it should:

```
Compressing project...
29.2 MB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Node.js runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Package found: /programs/server/package.json
Installing node 0.10.40
Installing npm 3.8.0
Installing packages from /programs/server/package.json
WARN: npm-shrinkwrap.json will override dependencies declared in package.json.

> fibers@1.0.5 install /mnt/input/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
meteor-dev-bundle@0.0.0 /mnt/input/programs/server
├── fibers@1.0.5
├─┬ meteor-promise@0.5.0
│ └─┬ promise@7.0.4
│   └── asap@2.0.3
├── semver@4.1.0
├─┬ source-map-support@0.3.2
│ └─┬ source-map@0.1.32
│   └── amdefine@1.0.0
└── underscore@1.5.2

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
v0.10.40
deploy -> v0.10.40
Uploading completed build.
Provisioning and deploying bundle to servos...
```

Any idea here?
Please ...

**Comment by eXon** [comment]
@tomitrescak This is because your dependencies of your package.json are probably not installed on your server. mup deson't have this problem, I'm not sure why modulus has it. Can you open a different issue about this?

**Comment by tomitrescak** [comment]
Ok, I have reverted to the previous version of Webpack for now.
Iguess the problem is the "modulus deploy" util that does not install dependencies.
